apiVersion: apps/v1
kind: Deployment
metadata:
  name: mk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mk-app
  template:
    metadata:
      labels:
        app: mk-app
    spec:
      containers:
      - name: mk-app-container
        image: 8083-nexus-tecdmwng.ldapowner.opsera.io/test-repo-pari/mkdockertest12:latest12
        ports:
        - containerPort: 8080
---        
apiVersion: v1
kind: Service
metadata:
  name: mk-app-service
spec:
  selector:
    app: mk-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
    
        
