apiVersion: apps/v1
kind: Deployment
metadata:
  name: mk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mk-app
  template:
    metadata:
      labels:
        app: mk-app
    spec:
      containers:
      - name: mk-app-container
        image: dockerfile:latest
        ports:
        - containerPort: 8080
    
        
